name: Discounts

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: discounts

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: python
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.com
          service: storedog-discounts

      - name: Install dependencies
        working-directory: ./services/discounts
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./services/discounts
        run: |
          ddtrace-run python -m unittest discover -p 'test*.py' -v
